### PR TITLE
BUG/FIX: Incorrect use of subscription ID as the Customer ID

### PR DESCRIPTION
**Pull request by eighty20results**

### CODE REVIEW

**Comment by positivejam** [comment]
@eighty20results, do you happen to know why this was never merged? From just reading the code, I can't figure out how this plugin would work without your fix in the PR. Are you by chance using this code in production yourself?

**Comment by eighty20results** [comment]
Sorry @positivejam, I don't have any insight into how PMPro manages their release process (and bug backlog). I do not believe there is an actual process, which makes it frustrating to submit and track bugs/pull requests.

**Comment by positivejam** [comment]
Okay, that's unfortunate. Thanks for responding.

**Comment by positivejam** [comment]
To whom it may concern: I think this PR can be closed, because [this other PR](https://github.com/strangerstudios/pmpro-stripe-billing-limits/pull/3) has been merged to master, and it fixes the same problem.

**Pull request closed without merging**
